# -*- coding: utf8 -*-
from MIRA.IWG2.models.Exame import Exame
from django.db import models

class Ct(models.Model):
    codima       = models.AutoField ( primary_key=True , auto_created=True, unique=True, verbose_name = 'PK Ct')
    exame_codexa = models.ForeignKey(Exame, db_column='exame_codexa')
    latera       = models.CharField(max_length=16, blank=True)
    pospac       = models.CharField(max_length=16, blank=True)
    frarefuid    = models.CharField(max_length=64, blank=True)
    indposref    = models.CharField(max_length=64, blank=True)
    numimg       = models.CharField(max_length=12, blank=True)
    oripac       = models.CharField(max_length=32, blank=True)
    datima       = models.DateField(null=True, blank=True)
    horima       = models.TimeField(null=True, blank=True)
    esppix       = models.CharField(max_length=32)
    oriima       = models.CharField(max_length=101)
    posima       = models.CharField(max_length=50)
    dissli       = models.CharField(max_length=16, blank=True)
    numlin       = models.SmallIntegerField()
    numcol       = models.SmallIntegerField()
    pixrep       = models.SmallIntegerField()
    placon       = models.SmallIntegerField(null=True, blank=True)
    pixasprat    = models.CharField(max_length=24, blank=True)
    rpcltdes     = models.TextField(blank=True)
    gpcltdes     = models.TextField(blank=True)
    bpcltdes     = models.TextField(blank=True)
    rpcltdat     = models.TextField(blank=True)
    gpcltdat     = models.TextField(blank=True)
    bpcltdat     = models.TextField(blank=True)
    conbolage    = models.CharField(max_length=64, blank=True)
    imgtyp       = models.TextField()
    samperpix    = models.SmallIntegerField()
    phoint       = models.CharField(max_length=16)
    bitall       = models.SmallIntegerField()
    bitsto       = models.SmallIntegerField()
    higbit       = models.SmallIntegerField()
    resint       = models.CharField(max_length=16)
    resslo       = models.CharField(max_length=16)
    kvp          = models.CharField(max_length=16, blank=True)
    acqnum       = models.CharField(max_length=8, blank=True)
    sopinsuid    = models.CharField(max_length=64, blank=True)
    icoima       = models.TextField(blank=True)
    sernum       = models.CharField(max_length=12, blank=True)
    tamima       = models.BigIntegerField()
    trasyn       = models.SmallIntegerField(null=True, blank=True)
    lutdes       = models.TextField(blank=True)
    lutdata      = models.TextField(blank=True)
    wincen       = models.TextField(blank=True)
    winwid       = models.TextField(blank=True)
    arqdvd       = models.NullBooleanField(null=True, blank=True)
    pathimg      = models.CharField(max_length=255, blank=True)
    seruid       = models.CharField(max_length=64, blank=True)
    imalau       = models.SmallIntegerField(null=True, blank=True)
    class Meta:        
        ordering = ('codima',)
        verbose_name = 'Ct'
        verbose_name_plural = 'Cts'
        db_table = u'ct'
        app_label = 'IWG2'