# -*- coding: utf8 -*-
from MIRA.IWG2.models.Exame import Exame
from django.db import models

class Mg(models.Model):
    codima       = models.AutoField ( primary_key=True , auto_created=True, unique=True, verbose_name = 'PK Mg')
    exame_codexa = models.ForeignKey(Exame, db_column='exame_codexa')
    latera       = models.CharField(max_length=16, blank=True)
    pospac       = models.CharField(max_length=16, blank=True)
    modality     = models.CharField(max_length=16, blank=True)
    refsopclauid = models.CharField(max_length=64, blank=True)
    refsopinsuid = models.CharField(max_length=64, blank=True)
    preinttyp    = models.CharField(max_length=64, blank=True)
    frarefuid    = models.CharField(max_length=64, blank=True)
    indposref    = models.CharField(max_length=64, blank=True)
    numimg       = models.CharField(max_length=12, blank=True)
    oripac       = models.CharField(max_length=32, blank=True)
    datima       = models.DateField(null=True, blank=True)
    horima       = models.TimeField(null=True, blank=True)
    samperpix    = models.SmallIntegerField()
    phoint       = models.CharField(max_length=16)
    numlin       = models.SmallIntegerField()
    numcol       = models.SmallIntegerField()
    bitall       = models.SmallIntegerField()
    bitsto       = models.SmallIntegerField()
    higbit       = models.SmallIntegerField()
    pixrep       = models.SmallIntegerField()
    placon       = models.SmallIntegerField(null=True, blank=True)
    pixasprat    = models.CharField(max_length=24, blank=True)
    rpcltdes     = models.TextField(blank=True)
    gpcltdes     = models.TextField(blank=True)
    bpcltdes     = models.TextField(blank=True)
    rpcltdat     = models.TextField(blank=True)
    gpcltdat     = models.TextField(blank=True)
    bpcltdat     = models.TextField(blank=True)
    conbolage    = models.CharField(max_length=64, blank=True)
    imalat       = models.CharField(max_length=16, blank=True)
    imgtyp       = models.TextField()
    pixintrel    = models.CharField(max_length=16)
    pixintrelsig = models.SmallIntegerField()
    resint       = models.CharField(max_length=16)
    resslo       = models.CharField(max_length=16)
    restyp       = models.CharField(max_length=64)
    preslutsha   = models.CharField(max_length=16, blank=True)
    losimgcom    = models.CharField(max_length=16, blank=True)
    losimgcomra  = models.TextField(blank=True)
    burinano     = models.CharField(max_length=16, blank=True)
    lutdat       = models.TextField(blank=True)
    wincen       = models.TextField(blank=True)
    winwid       = models.TextField(blank=True)
    dettyp       = models.CharField(max_length=16, blank=True)
    fievieori    = models.CharField(max_length=32, blank=True)
    fievierot    = models.CharField(max_length=16, blank=True)
    fieviehorfli = models.CharField(max_length=16, blank=True)
    imapixspa    = models.CharField(max_length=32)
    postyp       = models.CharField(max_length=16)
    orgexp       = models.CharField(max_length=16)
    overow       = models.SmallIntegerField(null=True, blank=True)
    ovecol       = models.SmallIntegerField(null=True, blank=True)
    ovetyp       = models.CharField(max_length=16, blank=True)
    oveori       = models.TextField(blank=True)
    ovebitall    = models.SmallIntegerField(null=True, blank=True)
    ovebitpos    = models.SmallIntegerField(null=True, blank=True)
    ovedat       = models.TextField(blank=True)
    sopinsuid    = models.CharField(max_length=64, blank=True)
    icoima       = models.TextField(blank=True)
    sernum       = models.CharField(max_length=12, blank=True)
    tamima       = models.BigIntegerField()
    trasyn       = models.SmallIntegerField(null=True, blank=True)
    lutdes       = models.TextField(blank=True)
    lutdata      = models.TextField(blank=True)
    arqdvd       = models.NullBooleanField(null=True, blank=True)
    pathimg      = models.CharField(max_length=255, blank=True)
    seruid       = models.CharField(max_length=64, blank=True)
    imalau       = models.SmallIntegerField(null=True, blank=True)
    class Meta:        
        ordering = ('codima',)
        verbose_name = 'Mg'
        verbose_name_plural = 'Mgs'
        db_table = u'mg'
        app_label = 'IWG2'